name: Digital Triangle Creative
favicon: null
layout_spectrum: 0.44863938982598484
typography_spectrum: 0.06004967796616256
title: Digital Triangle Creative
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2969643098767847
  lightness: 0.207736789714545
  saturation: 0.9907283403445035
  rhythmicContrast: 0.5330133170355111
purpose: []
